'use client';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {ArrowLeft,ArrowRight,ArrowUpRight,Expand} from 'lucide-react';
import {Carousel,CarouselContent,CarouselItem,type CarouselApi} from '@/components/ui/carousel';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Carousel_003} from '@/components/ui/skiper49';
import {mountScrollcraft} from '@/lib/scrollcraft';

function Depth({children,className=''}:{children:ReactNode;className?:string}){
 const ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{const root=ref.current;if(!root)return;let live=true;mountScrollcraft(root).then(api=>{if(live){api.layout();api.read();}}).catch(()=>{});return()=>{live=false;};},[]);
 return <div ref={ref} className={`media-depth ${className}`}><section data-sc-act="flow">{children}</section></div>;
}
const sites=[
 {name:'Heritage Collision',type:'COMMERCIAL VEHICLE REPAIR',image:'heritage-collision',url:'https://heritagecce.com/',description:'Help fleet owners understand the repair options and start an estimate.'},
 {name:'Total Detailing',type:'VEHICLE CARE & PROTECTION',image:'total-detailing',url:'https://totaldetailingpa.com/',description:'Give vehicle owners a clear way to explore protection, detailing, and their next appointment.'},
 {name:'RTV AI Studios',type:'VIDEO & CREATIVE PRODUCTION',image:'rtv-studios',url:'https://rtvaistudios.com/',description:'Let the films show what’s possible, then make starting a project simple.'},
 {name:'Heritage Coach',type:'SPECIALTY VEHICLE SALES',image:'heritage-coach',url:'https://www.heritagecoach.com/',description:'Help buyers browse available vehicles and connect with the people behind them.'},
 {name:'Pride Family Realty',type:'REAL ESTATE',image:'pride-realty',url:'https://pridefamilyrealty.com/',description:'Introduce the team and give buyers and sellers a clear place to begin.'}
];
export function WebsiteShowcase(){
 const [api,setApi]=useState<CarouselApi>(),[selected,setSelected]=useState(0);
 useEffect(()=>{if(!api)return;const update=()=>setSelected(api.selectedScrollSnap());update();api.on('select',update);return()=>{api.off('select',update);};},[api]);
 return <Depth className="website-showcase"><div className="showcase-heading"><div><p className="eyebrow">WEBSITES IN THE REAL WORLD</p><h2>Different businesses.<br/>A clearer way forward.</h2></div><p>Explore five websites. Choose a business, see the work, and open the site for a closer look.</p></div><Carousel setApi={setApi} opts={{loop:true,duration:22}} aria-label="Website portfolio" className="portfolio-carousel"><div className="portfolio-backplane" aria-hidden="true"/><CarouselContent>{sites.map((site,i)=><CarouselItem key={site.name} aria-label={`${i+1} of ${sites.length}: ${site.name}`} aria-hidden={selected!==i} inert={selected!==i}><div className="browser-frame"><div className="browser-topline"><span aria-hidden="true">● ● ●</span><span>{new URL(site.url).hostname.replace('www.','')}</span><ArrowUpRight size={13}/></div><img src={`/media/portfolio/${site.image}.webp`} alt={`${site.name} website homepage`} width="1357" height="933" loading="lazy"/></div><div className="project-foreground"><div><span>{site.type}</span><h3>{site.name}</h3><p>{site.description}</p></div><a className="button copper" href={site.url} target="_blank" rel="noreferrer">View website <ArrowUpRight size={18}/></a></div></CarouselItem>)}</CarouselContent><div className="portfolio-controls"><span aria-live="polite">{String(selected+1).padStart(2,'0')} <span>/ 05</span></span><div><button onClick={()=>api?.scrollPrev()} aria-label="Previous website"><ArrowLeft size={20}/></button><button onClick={()=>api?.scrollNext()} aria-label="Next website"><ArrowRight size={20}/></button></div></div></Carousel><div className="project-selectors" aria-label="Choose a website">{sites.map((site,i)=><button key={site.name} onClick={()=>api?.scrollTo(i)} aria-label={`Show ${site.name} website`} aria-pressed={selected===i}><span>0{i+1}</span>{site.name}</button>)}</div></Depth>;
}
const films=[
 {id:'cars-commercial',poster:'cars-poster',name:'Impossible',type:'CARS COMMERCIAL',duration:'1:18',description:'A cinematic car commercial from RTV AI Studios. An unexpected setting gives a familiar subject a second look.'},
 {id:'rtv-studio',poster:'rtv-studio-poster',name:'RTV AI Studios',type:'STUDIO COMMERCIAL',duration:'2:02',description:'A commercial introducing RTV AI Studios and its creative possibilities.'},
 {id:'comfort-solutions',poster:'comfort-solutions-poster',name:'Comfort Solutions',type:'SERVICE BUSINESS COMMERCIAL',duration:'0:41',description:'A commercial for Comfort Solutions. A service business brought to life through video.'}
];
export function CreativeGallery(){
 const [opened,setOpened]=useState<number|null>(null),[failed,setFailed]=useState(false);const video=useRef<HTMLVideoElement>(null);const trigger=useRef<HTMLButtonElement|null>(null);const film=opened===null?null:films[opened];
 function close(){video.current?.pause();setOpened(null);setFailed(false);}
 return <section className="creative-gallery compact-film-gallery" id="films"><div className="media-section-heading"><div><p className="eyebrow">COMMERCIAL FILMS</p><h2>Worth a closer look.</h2></div><p>Swipe through the films. Choose one to watch.</p></div><Carousel_003 images={films.map(f=>({src:`/media/creative/${f.poster}.jpg`,alt:`${f.name} commercial poster`,title:f.name,duration:f.duration}))} onSelect={(i,button)=>{trigger.current=button;setFailed(false);setOpened(i);}}/><a className="carousel-credit" href="https://gxuri.me" target="_blank" rel="noreferrer">Carousel by Skiper UI</a><Dialog open={opened!==null} onOpenChange={value=>{if(!value)close();}}><DialogContent className="film-player-dialog" onCloseAutoFocus={e=>{e.preventDefault();trigger.current?.focus();}}>{film&&<><div className="film-player-heading"><span>{film.type}</span><DialogTitle>{film.name}</DialogTitle></div><video ref={video} key={film.id} controls autoPlay playsInline preload="metadata" poster={`/media/creative/${film.poster}.jpg`} src={`/media/creative/${film.id}.mp4`} aria-label={`${film.name} commercial`} onError={()=>setFailed(true)}/><DialogDescription>{film.description}</DialogDescription>{failed&&<p role="alert">The film couldn’t load. <a href={`/media/creative/${film.id}.mp4`}>Open the video directly</a>.</p>}</>}</DialogContent></Dialog></section>;
}
const ads=[
 {name:'Daybreak Coffee',image:'daybreak-ad',headline:'Tomorrow starts here.',description:'Make an everyday ritual feel worth looking forward to. Product, color, and one clear idea do the work.',alt:'Daybreak Coffee concept ad: Tomorrow starts here. Freshly roasted. Ready for your ritual. Espresso pouring into a cobalt cup. Find your next bag.'},
 {name:'Stillwell Outdoors',image:'stillwell-ad',headline:'Your weekends deserve this view.',description:'Help homeowners picture what they want their space to feel like, before asking them to plan it.',alt:'Stillwell Outdoors concept ad: Your weekends deserve this view. Outdoor spaces made for slowing down. Garden terrace with two chairs at sunset. Plan your outdoor space.'}
];
export function AdGallery(){const [open,setOpen]=useState<number|null>(null);return <><Depth className="ad-gallery"><div className="ad-intro"><p className="eyebrow">STILL IMAGES. A STRONG FIRST IMPRESSION.</p><h2>One image.<br/>A reason to care.</h2><p>Different businesses need different creative. These original concepts show how the image and message can work together.</p></div><div className="ad-pair">{ads.map((ad,i)=><article className={`ad-piece ad-piece-${i}`} key={ad.name}><button onClick={()=>{document.querySelectorAll('video').forEach(v=>v.pause());setOpen(i);}} aria-label={`Enlarge ${ad.name} concept ad`}><img src={`/media/${ad.image}.webp`} alt={ad.alt} width="1122" height="1402" loading="lazy"/><span><Expand size={18}/> View ad</span></button><div><span className="concept-label">Concept ad · Fictional brand</span><h3>{ad.name}</h3><p>{ad.description}</p></div></article>)}</div></Depth><Dialog open={open!==null} onOpenChange={v=>{if(!v)setOpen(null);}}><DialogContent className="ad-dialog">{open!==null&&<><DialogTitle>{ads[open].name}</DialogTitle><DialogDescription>Original concept ad for a fictional brand.</DialogDescription><img src={`/media/${ads[open].image}.webp`} alt={ads[open].alt} width="1122" height="1402"/></>}</DialogContent></Dialog></>;
}
