'use client';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {ArrowDown,ArrowRight,ArrowUpRight,Check,ContactRound,Mail,MessageSquare,ClipboardCheck,UserRound,CalendarClock,Globe,Film,Handshake} from 'lucide-react';
import {mountScrollcraft} from '@/lib/scrollcraft';
import {capabilities,serviceHref} from '@/lib/services';

export function LayerTrack({children,className=''}:{children:ReactNode;className?:string}){const root=useRef<HTMLDivElement>(null);useEffect(()=>{const el=root.current;if(!el)return;let alive=true;let observer:ResizeObserver|undefined;mountScrollcraft(el).then(api=>{if(!alive)return;observer=new ResizeObserver(()=>api.layout());observer.observe(el);api.layout();api.read();}).catch(()=>{});return()=>{alive=false;observer?.disconnect();};},[]);return <div ref={root} className={`layer-track ${className}`}>{children}</div>;}

const contextParts=[
 {title:'The inquiry',icon:Globe,source:'From your website',note:'“I’d like to talk about a project.”',heading:'Start with what they need.',body:'The details someone shares on your website arrive with the inquiry. Your team starts with context instead of another blank contact.',fields:[['Interested in','A new project'],['Came from','Website inquiry'],['Contact preference','Email first']]},
 {title:'The conversation',icon:MessageSquare,source:'From your team',note:'“We talked through the options.”',heading:'Keep the conversation together.',body:'Give the next person the history: what the customer asked, what you discussed, and what still needs an answer.',fields:[['Discussed','Goals and possible options'],['Customer asked','What should I prepare?'],['Team note','Send the relevant examples']]},
 {title:'The next step',icon:CalendarClock,source:'From your process',note:'“Send examples, then check in.”',heading:'Make the next move visible.',body:'Agree who follows up and what they need to do. A useful CRM makes responsibility clear instead of relying on someone’s memory.',fields:[['Responsible','Assigned team member'],['Next action','Send examples'],['Follow-up','Schedule a check-in']]}
];
export function CustomerContextDemo(){const [active,setActive]=useState(0);const part=contextParts[active];return <LayerTrack className="context-demo"><section data-sc-act="flow"><div className="workflow-heading"><p className="eyebrow">CUSTOMER INFORMATION, CONNECTED</p><h2>One inquiry.<br/>The whole conversation.</h2><p>Choose a piece of the example to see what your team can keep together.</p></div><div className="context-workspace"><div className="context-inputs" role="group" aria-label="Explore customer information">{contextParts.map((p,i)=>{const Icon=p.icon;return <button key={p.title} aria-pressed={active===i} aria-controls="customer-example" onClick={()=>setActive(i)}><span className="source-icon"><Icon size={21}/></span><div><small>{p.source}</small><strong>{p.title}</strong><p>{p.note}</p></div><ArrowRight size={20}/></button>;})}</div><div className="context-join" aria-hidden="true"><span/><ContactRound size={32}/><span/></div><div className="customer-record" id="customer-example" aria-live="polite"><div className="record-header"><span><ContactRound size={20}/> Customer context</span><small>EXAMPLE</small></div><div className="record-tabs" aria-hidden="true">{contextParts.map((p,i)=><span key={p.title} className={i===active?'selected':''}>{p.title}</span>)}</div><div className="record-body" key={active}><h3>{part.heading}</h3><p>{part.body}</p><dl>{part.fields.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></div><div className="record-outcome"><Check size={19}/><span>Useful context. A clear owner. An agreed next step.</span></div></div></div><p className="example-footnote">Example information. Your fields, stages, and tools are shaped around your business.</p></section></LayerTrack>;}

const followSteps=[
 {title:'Inquiry arrives',icon:Mail,owner:'Your connected tools',heading:'Get the inquiry to the right person.',description:'Capture the request and notify the person responsible. Start with what the customer actually asked.',label:'CUSTOMER INQUIRY',message:'Hi, I’m interested in a project. Could you tell me how to get started?',action:'Capture the details and assign an owner',tag:'Received'},
 {title:'Prepare a reply',icon:MessageSquare,owner:'AI assistance',heading:'Start from a useful draft.',description:'AI can summarize the request and help draft a response using your approved information and tone.',label:'DRAFT FOR YOUR TEAM',message:'Thanks for getting in touch. Could you tell us a little about what you have in mind and a good time to talk?',action:'Keep the draft ready for review',tag:'Not sent'},
 {title:'Your team reviews',icon:ClipboardCheck,owner:'A person on your team',heading:'Keep your judgment in the loop.',description:'Check the details, adjust the wording, and approve the next step. Decide together which actions need a person.',label:'REVIEW BEFORE SENDING',message:'Is this accurate? Does it answer their question? Does it sound like us?',action:'Your team approves or edits the response',tag:'Human review'},
 {title:'Keep it moving',icon:Handshake,owner:'Your process + your team',heading:'Follow the conversation, not just a timer.',description:'If they reply, route it to a person. If they need more time, use an agreed reminder or follow-up. Stop when it is no longer useful.',label:'THE NEXT CONNECTION',message:'Customer replies → let the team know.\nNo reply yet → keep the agreed reminder visible.',action:'A clear next step, even on a busy day',tag:'Owned follow-up'}
];
export function FollowupDemo(){const [active,setActive]=useState(0);const step=followSteps[active];const Icon=step.icon;return <LayerTrack className="followup-demo"><section data-sc-act="flow"><div className="workflow-heading"><p className="eyebrow">FROM INTEREST TO A REAL CONVERSATION</p><h2>A next step.<br/>Not another loose end.</h2><p>Walk through an example. See where your tools help and where your team takes over.</p></div><div className="followup-workspace"><div className="followup-stations" role="group" aria-label="Explore the follow-up workflow">{followSteps.map((s,i)=>{const I=s.icon;return <button key={s.title} aria-pressed={active===i} aria-controls="followup-example" onClick={()=>setActive(i)}><span><I size={20}/></span><div><small>0{i+1}</small><strong>{s.title}</strong></div>{i<3&&<ArrowDown className="station-arrow" size={18}/>}</button>;})}</div><div className="followup-explanation" id="followup-example" aria-live="polite"><div className="followup-owner"><Icon size={20}/>{step.owner}</div><h3>{step.heading}</h3><p>{step.description}</p><div className="message-sheet" key={active}><div><span>{step.label}</span><small>{step.tag}</small></div><p>{step.message}</p><footer><Check size={18}/>{step.action}</footer></div><span className="example-footnote">Example workflow. This demonstration does not send messages.</span></div></div></section></LayerTrack>;}

export function ConnectedHandoff({home=false}:{home?:boolean}){return <LayerTrack className="connected-handoff"><section data-sc-act="flow"><div className="handoff-intro"><h2>Make the next<br/>step connect.</h2><p>Attention matters more when it has somewhere useful to go. Connect the work your customer sees to the information your team needs.</p><a className="text-link" href={home?'/services/connected-system':'#connected-journey'}>{home?'Explore the full system':'See each connection'}<ArrowUpRight size={18}/></a></div><div className="handoff-planes"><a href="/services/creative" className="handoff-plane handoff-attention"><div className="handoff-image"><img src="/media/daybreak-ad.webp" alt="Daybreak Coffee concept ad for a fictional brand" width="1122" height="1402" loading="lazy"/></div><div><span>01 / AD CREATIVE</span><h3>“That caught my eye.”</h3><p>A clear message earns a closer look.</p></div><ArrowUpRight size={20}/></a><a href="/services/websites" className="handoff-plane handoff-interest"><img src="/media/total-project.jpg" alt="Total Detailing website project" width="1353" height="929" loading="lazy"/><div><span>02 / WEBSITE</span><h3>“This could help me.”</h3><p>Your website answers the next question.</p></div><ArrowUpRight size={20}/></a><a href="/services/crm" className="handoff-plane handoff-context"><ContactRound size={31}/><div><span>03 / CRM</span><h3>Know what they need.</h3><p>The inquiry and its context reach your team.</p></div><ArrowUpRight size={20}/></a><a href="/services/follow-up" className="handoff-plane handoff-response"><MessageSquare size={31}/><div><span>04 / FOLLOW-UP</span><h3>Keep the conversation going.</h3><p>A useful response. An owner for the next step.</p></div><ArrowUpRight size={20}/></a></div></section></LayerTrack>;}

const serviceIcons=[Film,Globe,ContactRound,MessageSquare];
export function ServiceStack(){return <LayerTrack className="service-stack"><section className="service-stack-section" id="services"><div className="stack-intro"><p className="eyebrow">START WITH WHAT NEEDS WORK</p><h2>One missing piece.<br/>Or the whole picture.</h2><p>Choose one service for a specific problem. Connect them when the handoffs need work, too.</p><a className="button copper" href="/services/connected-system">Explore the full system<ArrowUpRight size={18}/></a></div><div className="stack-options">{capabilities.slice(0,4).map((s,i)=>{const Icon=serviceIcons[i];return <article key={s.slug} className={`service-sheet service-sheet-${i}`} data-sc-act="flow"><div className="service-sheet-top"><span>0{i+1}</span><Icon size={30} strokeWidth={1.3}/></div><h3>{s.verb}</h3><p>{s.detail}</p><a href={serviceHref(s.slug)}>{s.label==='Website'?'Websites & databases':s.slug==='crm'?'CRM setups':s.label}<ArrowUpRight size={22}/></a></article>;})}</div></section></LayerTrack>;}
