import type {Metadata} from 'next';
import {notFound} from 'next/navigation';
import {ArrowRight,ArrowUpRight,Film,Globe,ContactRound,MessageCircle,Handshake} from 'lucide-react';
import SiteHeader from '@/components/site-header';
import {CustomerContextDemo,FollowupDemo,ConnectedHandoff} from '@/components/workflow-scenes';
import {WebsiteShowcase,CreativeGallery,AdGallery} from '@/components/service-media';
import {capabilities,serviceHref,inquiryHref} from '@/lib/services';
const content={
 creative:{title:'Creative that earns a closer look.',intro:'Help people understand what makes your business worth their attention. Turn your offer, expertise, and real work into videos, ads, and social content.',problem:'Good work deserves to be seen.',body:'When people are scrolling past, you have a small window to make your offer clear. Give them something relevant to notice—and a reason to take the next step.',question:'What do you want people to notice?',cta:'Talk about your creative',next:'A good ad needs somewhere good to land.'},
 websites:{title:'A website that helps people choose you.',intro:'Attract the right visitors, keep their interest, and make it easy to become an inquiry. Connect the details they share to the people who need them.',problem:'Make the next step feel obvious.',body:'Your customers should be able to understand what you offer, see why it matters, and contact you without hunting for an answer. Your team should receive useful information when they do.',question:'What should your website do better?',cta:'Talk about your website',next:'An inquiry is the beginning. Give it a place to go.'},
 crm:{title:'Know your customers. Know what’s next.',intro:'Put contact details, conversations, and opportunities in one useful place. Set up a CRM—a customer relationship management system—that fits how your business works.',problem:'Less searching. A clearer next step.',body:'When customer information lives in inboxes, spreadsheets, and someone’s memory, follow-up gets harder than it needs to be. Give your team a shared view of the customer and who is responsible for the next move.',question:'Where does customer information get stuck?',cta:'Talk about your CRM',next:'Knowing the next step helps. Making it happen matters.'},
 'follow-up':{title:'Make it easier to keep the conversation going.',intro:'Help your team respond to inquiries, remember a check-in, and follow through. Use thoughtful automation and AI assistance to support the people doing the work.',problem:'Good interest shouldn’t disappear into a busy day.',body:'A missed reminder or a conversation with no clear owner can leave a potential customer waiting. Build a practical follow-up process around the way people buy from you.',question:'Which conversations need better follow-through?',cta:'Talk about your follow-up',next:'Bring the whole customer journey together.'},
 'connected-system':{title:'From their first look to your next customer.',intro:'Creative gets attention. Your website builds interest. Your CRM keeps the context. Follow-up helps your team turn that interest into a useful sales conversation.',problem:'Your customer sees one business. Make it feel that way.',body:'An ad, a website, and a sales tool each have a job. Connecting them means the offer stays clear, customer information reaches your team, and the next step has an owner.',question:'What would a more connected business look like?',cta:'Talk about your full system',next:'Start with the part your business needs most.'}
};
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const c=content[slug as keyof typeof content];return c?{title:`${c.title} | Relevaint`,description:c.intro,alternates:{canonical:`/services/${slug}`}}:{};}
export function generateStaticParams(){return capabilities.map(({slug})=>({slug}));}
export const dynamicParams=false;
export default async function ServicePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const index=capabilities.findIndex(s=>s.slug===slug);if(index<0)notFound();const service=capabilities[index];const c=content[service.slug];const next=capabilities[(index+1)%5];return <><SiteHeader/><main id="main" className={`service-page service-page-${slug}`}><section className="service-page-hero"><a className="service-back" href={`/?step=${slug}#journey`}>← Back to your business journey</a><div className="service-hero-grid"><div><p className="eyebrow">{String(index+1).padStart(2,'0')} / {slug==='connected-system'?'THE FULL SYSTEM':service.label.toUpperCase()}</p><h1>{c.title}</h1></div><div className="service-hero-intro"><p>{c.intro}</p><a className="button copper" href={inquiryHref(slug)}>{c.cta}<ArrowUpRight size={17}/></a><span>{slug==='connected-system'?'Connect the whole journey, or begin with one service.':'Available on its own or as part of a connected system.'}</span></div></div></section>
<nav className="service-route-nav" aria-label="Customer journey">{capabilities.map((s,i)=><a key={s.slug} href={serviceHref(s.slug)} aria-current={slug===s.slug?'page':undefined}><span>0{i+1}</span>{s.label}{i<4&&<ArrowRight size={14}/>}</a>)}</nav>
<section className="service-problem"><h2>{c.problem}</h2><p>{c.body}</p></section>
{slug==='creative'&&<><CreativeGallery/><AdGallery/><section className="service-scope"><div><p className="eyebrow">CHOOSE THE RIGHT FORMAT</p><h2>Show your value.<br/>In a way people watch.</h2></div><div className="scope-rows">{[['Ad creative','A clear hook, a relevant offer, and a next step. Creative built for the campaign and channel you choose.'],['Promotional & explainer videos','Show what you do, explain how it helps, and make a complex offer easier to understand.'],['Social content & workflows','Give your business a consistent presence, with a practical process for creating, reviewing, and publishing.']].map(([t,b])=><article key={t}><h3>{t}</h3><p>{b}</p></article>)}</div></section><section className="service-note"><h3>Start with your business, not a blank content calendar.</h3><p>Bring your offer, existing footage, customer questions, or an idea you want to explain. We’ll agree on the message, formats, production approach, and review process before creating.</p></section></>}
{slug==='websites'&&<><WebsiteShowcase/><section className="website-jobs">{[['Attract','Give your business a clear, credible presence that matches the message that brought someone here.'],['Keep','Answer the questions customers actually have. Show your services, your value, and work they can trust.'],['Convert','Make contacting, booking, or requesting a quote easy, with a clear next step and useful confirmation.']].map(([t,b],i)=><article key={t}><span>0{i+1}</span><h3>{t}.</h3><p>{b}</p></article>)}</section><section className="data-connection"><div><p className="eyebrow">BEHIND THE WEBSITE</p><h2>The details they share.<br/>Ready for your business.</h2><p>A connected database gives customer information a useful home. Inquiry details can be stored, organized, and passed to your CRM or team, with access and integrations agreed around your tools.</p></div><ol><li><span>Customer submits</span><strong>Name, contact details, and what they need</strong></li><li><span>Your website stores</span><strong>A structured record in a connected database</strong></li><li><span>Your team receives</span><strong>The context to respond and take the next step</strong></li></ol></section></>}
{slug==='crm'&&<><CustomerContextDemo/><section className="crm-compare"><div><span className="eyebrow">OPTION 01</span><h2>Set up a tool<br/>that already exists.</h2><p>Get an off-the-shelf CRM configured around your contacts, sales stages, team responsibilities, and follow-up process.</p><ul><li>Choose or improve an existing platform</li><li>Organize customer fields and sales stages</li><li>Set up ownership, reminders, and useful views</li></ul><strong>A good fit when an established tool can cover your needs.</strong></div><div><span className="eyebrow">OPTION 02</span><h2>Build around<br/>the way you work.</h2><p>Explore a custom customer management system when your workflow or information needs call for a more tailored approach.</p><ul><li>Map the information your business needs</li><li>Design views around your team’s daily work</li><li>Connect agreed tools and customer touchpoints</li></ul><strong>A good fit when your requirements justify a custom build.</strong></div></section><section className="service-scope"><div><p className="eyebrow">THE PRACTICAL DIFFERENCE</p><h2>One customer.<br/>The useful context.</h2></div><div className="scope-rows">{[['Who they are','Contact details, the business or household they belong to, and what they’re interested in.'],['Where things stand','The conversation so far, the opportunity stage, and any information your team needs before responding.'],['What happens next','A clear owner, a task or reminder, and an agreed next step.']].map(([t,b])=><article key={t}><h3>{t}</h3><p>{b}</p></article>)}</div></section></>}
{slug==='follow-up'&&<><FollowupDemo/><section className="service-note"><h3>Your voice. Your boundaries. Your relationships.</h3><p>Agree on what can happen automatically, what needs approval, when a person takes over, and how customers can stop messages. AI assists with the work; your team stays responsible for the conversation.</p></section><section className="website-jobs">{[['Respond','Help the right person answer with the information they need.'],['Remember','Use tasks and reminders to make the next step visible.'],['Reconnect','Build relevant email or text follow-up around the way your customers decide.']].map(([t,b],i)=><article key={t}><span>0{i+1}</span><h3>{t}.</h3><p>{b}</p></article>)}</section></>}
{slug==='connected-system'&&<><ConnectedHandoff/><section className="connected-map" id="connected-journey"><div className="connected-map-heading"><p className="eyebrow">FIVE STEPS. ONE BUSINESS.</p><h2>Make the handoffs<br/>work for you.</h2><p>Each piece solves a different problem. Together, they help your business carry the conversation forward.</p></div><ol>{capabilities.map((s,i)=>{const Icon=[Film,Globe,ContactRound,MessageCircle,Handshake][i];return <li key={s.slug}><span className="system-icon"><Icon size={24}/></span><div><span>0{i+1} / {s.label}</span><h3>{s.verb}</h3><p>{s.benefit}</p>{i<4&&<a className="text-link" href={serviceHref(s.slug)}>Explore this service <ArrowUpRight size={16}/></a>}</div></li>})}</ol></section><section className="service-note"><h3>Built to support your sales process.</h3><p>A sale still depends on your offer, the customer, and your team’s conversation. The system helps you make the most of that opportunity by keeping information and next steps connected.</p></section><section className="website-jobs">{[['Find the gap','Look at how someone discovers you, contacts you, and becomes a customer today.'],['Agree the scope','Choose one priority or a connected build. Define the tools, deliverables, responsibilities, and handoffs.'],['Connect & improve','Build and test the agreed path, help your team use it, and decide what should improve next.']].map(([t,b],i)=><article key={t}><span>0{i+1}</span><h3>{t}.</h3><p>{b}</p></article>)}</section></>}
<section className="service-next"><div><span>THE NEXT CONNECTION</span><h2>{c.next}</h2></div><a className="text-link" href={serviceHref(next.slug)}>{next.slug==='connected-system'?'See the connected system':`Explore ${next.label.toLowerCase()}`}<ArrowUpRight size={20}/></a></section><section className="service-final"><p className="eyebrow">START WHERE YOU NEED HELP</p><h2>{c.question}</h2><p>Bring the problem. We’ll work out a useful next step together.</p><a className="button copper" href={inquiryHref(slug)}>{c.cta}<ArrowUpRight size={17}/></a></section></main><footer className="service-footer"><a href="/" className="footer-brand" aria-label="Relevaint home"><img src="/media/relevaint-logo.png" alt="Relevaint" width="145" height="50"/></a><p>Your business. Improved.</p><a href="/#contact">Let’s talk <ArrowUpRight size={16}/></a></footer></>}
